import type { Metadata } from "next";
import {
    
    QuicksandFont,
    NunitoFont,
    dottedFont,
    TaylerSwiftFont,
} from "@/fonts/fonts.config";
import "./globals.css";

export const metadata: Metadata = {
    title: "2025 board",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={`${QuicksandFont.variable} ${NunitoFont.variable} ${TaylerSwiftFont.variable} ${dottedFont.variable}`}>
            <body>{children}</body>
        </html>
    );
}
