import type { Metadata } from "next";
import { Toaster } from 'sonner';
import {
    
    QuicksandFont,
    NunitoFont,
    dottedFont,
    TaylerSwiftFont,
    Shadows_Into_LightFont
} from "@/fonts/fonts.config";
import "./globals.css";

export const metadata: Metadata = {
    title: "2025 board",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={`${Shadows_Into_LightFont.variable} ${QuicksandFont.variable} ${NunitoFont.variable} ${TaylerSwiftFont.variable} ${dottedFont.variable}`}>
            <body>{children} <Toaster  position="top-center" richColors/></body>
        </html>
    );
}
